# @package _global_

defaults:
  # https://hydra.cc/docs/configure_hydra/logging/
  - supervisord/default
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

_target_: airflow_supervisor.SupervisorConfiguration
unix_http_server:
pinet_http_server:
include:
program:
group:
fcgiprogram:
eventlistener:
rpcinterface:
